install:
- mkdir travis-phantomjs
- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
- tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
- export PATH=$PWD/travis-phantomjs:$PATH
before_script:
- npm install
- bower install
script: gulp travis:test
deploy:
  provider: heroku
  api_key:
    secure: iTM2fQCeIpso54YKy8Z0fJbeqGXzPnbWqagsKLcRhp1noh2yQPd2MpweuVz6lNcv23Elc170xLtpiEogF6pGeTZKNpOv5wQBcbgvxjw3WcAKPAqADo10xTlAOgI8uKkY9eWtKDwt5Nd2aJNneYlae8vXjNBJOOUBwgC6/Zz4Q/xw7Coldb2Tlou66rKz9xd8gFA6fYXwIr8Rz2X+EzypDJz5g/us57xhwo3LGok5s2mpG3R5zXRczZZElz4q6QAiUuglM3VCHZWa/A8gAmeiymtUdIEPBBeA5Os0620QlOWV5izkM58oHnxVcNFeB23m5rMrVagOZLRKRXbCcRaGD/zrxs3rN5z+w/TmlrVKg3TmH8+bAO2vDYqnwZ1nxkK1ZBpnZCkUTTb+rDiT3ABSxHXV4kG1Ho7UUqTrINbFvtPtzd9P27Un13wjj8BkTqZN3+4Mi6LGnwK66F008S3klnK1iewkNd4mev0Q8fDL6jfRWEMNleYK//cwBeoPFyuxnNy6XOCdN7Y15p0MIg2JJFPJR6vOCFMsT+LfTECK/xdn3pAMY7CAJMx/3v7jL6s2BXDzqkeupzs2cahiMatwMVMJIQAAwptyqGEiIIRDqiSc8bVF5ICt1VDUVmBMTTs+qXvdkjBSXJffWMAYQzbfWxWBpxS22KnZab69MC+ivZk=
  app:
    master: my-app-travis
